@kfp(image=) to support customers who want to specify image per step (#120)
* Adding @kfp_step decorator.

* Ensuring the integration tests now pass.

* AIP-5075 (sub branch) - Creating two images to successfully test @kfp_step (#121)

* Adding PyYaml

* Formatting changes and adding more pip installs.

* Using CICD image.

* Removing userid

* Correct version of kfp.

* Addressing all PR comments.

* Resolving test failure.

* Running single test.

* Integration tests should now work.

* Adding datastore root values.

* Correctly exporting variable.

* Correct datastore.

* Adding image with correct Metaflow version.

* Adding image with correct Metaflow version.

* Hopefully works now

* Printing for debugging.

* Creating image 1.

* Creating image 2.

* Adding second docker image

* Ensuring KFP step flow passes.

* Removing the additional test step.

* Removing the additional test step.

* Final test.

* Adding back all tests.

* Removing old changes.

Co-authored-by: Hari Sezhiyan <hariharans@zillowgroup.com>

* Trigger Build

* AIP-5075 (sub branch) Checking for BASE_IMAGE with @kfp_step (#123)

* Adding check for BASE_IMAGE.

* Fixing build step.

* Adding code to address checking for BASE_IMAGE.

* Removing Parameter variable.

Co-authored-by: Hari Sezhiyan <hariharans@zillowgroup.com>

* Removing Python 2 from runner.

* Removing Python 2 tests.

* Removing Python2 tests.

* Yunw/reduce dockerfile (#124)

* Simplify docker file strcuture

* Correct typo in cicd

* Removing @kfp_step, keeping only @kfp

* Revert to 7e9b1e60cc7a6a984801a9b52f0c7e946e3e9640

* Changing @kfp_step to @kfp.

* Minor typos.

* Formatting issues resolved.

* Addressing PR comments.

* Removing kfp_step_flow.py

* Adding more clarity to the comments.

* Addressing final comments.

* Final instances of metaflow/plugins/kfp/tests/flows/kfp_flow.py

* Removing CICD image.

* Running pip install correctly.

* Addressing final comments.

* Typo and KFP_STEP_IMAGE -> IMAGE_TAG

Co-authored-by: Hari Sezhiyan <hariharans@zillowgroup.com>
Co-authored-by: Yun Wu <wuyun1618@gmail.com>

diff --git a/metaflow/plugins/kfp/tests/.gitlab-ci.yml b/metaflow/plugins/kfp/tests/.gitlab-ci.yml
--- a/metaflow/plugins/kfp/tests/.gitlab-ci.yml
+++ b/metaflow/plugins/kfp/tests/.gitlab-ci.yml
@@ -12,6 +12,7 @@ variables:
   MINOR_VERSION: "0"
   METAFLOW_VERSION_PATH: "setup.py"
   IMAGE_REPOSITORY_TAG_PATH: 'image_tag_file.txt'
+  IMAGE_REPOSITORY_TAG_PATH_KFP_STEP: 'image_tag_file_kfp_step.txt'
   # Run on the Internal cluster only on commit.
   # We run the tests via the integration test framework for Non-Prod/Prod.
   DEPLOY_INTERNAL: "true"
@@ -48,6 +49,7 @@ stages:
   script:
     - *path-to-host-file-directory  
     - export BUILT_IMAGE_FULL_PATH=$( cat ${IMAGE_REPOSITORY_TAG_PATH} )
+    - export BUILT_IMAGE_FULL_PATH_KFP_STEP=$( cat ${IMAGE_REPOSITORY_TAG_PATH_KFP_STEP} )
     - cp -r /root/.kube .
     - docker run
         --rm
@@ -60,6 +62,7 @@ stages:
         -e KFP_RUN_URL_PREFIX=$KFP_RUN_URL_PREFIX 
         -e KFP_SDK_NAMESPACE=$KFP_SDK_NAMESPACE 
         -e USER=$GITLAB_USER_EMAIL
+        -e KFP_STEP_IMAGE=${BUILT_IMAGE_FULL_PATH_KFP_STEP}
         ${BUILT_IMAGE_FULL_PATH}
         bash -c "
           cd /home/zservice/metaflow/metaflow/plugins/kfp/tests &&
@@ -76,7 +79,7 @@ build:docker:
   script:
     - *version
     - export IMAGE_REPOSITORY_TAG=${DOCKER_REPO_URL}/${CI_PROJECT_NAMESPACE}/${PY_LIBRARY_NAME}:${IMAGE_TAG}
-    - 'docker build --no-cache -f metaflow/plugins/kfp/tests/Dockerfile -t ${IMAGE_REPOSITORY_TAG} .'
+    - 'docker build --no-cache -f metaflow/plugins/kfp/tests/Dockerfile --build-arg IMAGE_TAG=${IMAGE_REPOSITORY_TAG} -t ${IMAGE_REPOSITORY_TAG} .'
     - 'echo ${DOCKER_API_KEY} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REPO_URL}'
     - STDERR=$(docker push ${IMAGE_REPOSITORY_TAG} 2>&1 >/dev/null) || true
     - echo $STDERR
@@ -88,9 +91,25 @@ build:docker:
         exit 1
       fi
     - echo ${IMAGE_REPOSITORY_TAG} > ${IMAGE_REPOSITORY_TAG_PATH}
+
+    # duplicate the above for another image to specifically test kfp_step_flow.py
+    - export IMAGE_REPOSITORY_TAG_KFP_STEP=${DOCKER_REPO_URL}/${CI_PROJECT_NAMESPACE}/${PY_LIBRARY_NAME}:${IMAGE_TAG}_kfp_step
+    - 'docker build --no-cache -f metaflow/plugins/kfp/tests/Dockerfile --build-arg IMAGE_TAG=${IMAGE_REPOSITORY_TAG_KFP_STEP} -t ${IMAGE_REPOSITORY_TAG_KFP_STEP} .'
+    - 'echo ${DOCKER_API_KEY} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REPO_URL}'
+    - STDERR=$(docker push ${IMAGE_REPOSITORY_TAG_KFP_STEP} 2>&1 >/dev/null) || true
+    - echo $STDERR
+    - |
+      if [ -z "$STDERR" ] || [[ $STDERR == *"manifest invalid"* ]]; then
+        echo "Successful!"
+      else
+        echo "Error in pushing image to Artifactory." >&2
+        exit 1
+      fi
+    - echo ${IMAGE_REPOSITORY_TAG_KFP_STEP} > ${IMAGE_REPOSITORY_TAG_PATH_KFP_STEP}
   artifacts:
     paths:
       - ${IMAGE_REPOSITORY_TAG_PATH}
+      - ${IMAGE_REPOSITORY_TAG_PATH_KFP_STEP}
 
 build:publish:
   extends: .aip_python_debian_image
